### ISSUE TITLE
代码报错

### ISSUE THREAD

**Issue by XueNianOfficial** [jcq15/bilibili_playcount#3]
![image](https://user-images.githubusercontent.com/52588960/181524459-3449fa59-d1d5-408e-8947-157465444d0e.png)
![image](https://user-images.githubusercontent.com/52588960/181524534-e0cbbcf5-1b03-424b-a20c-1c2bb6333ea3.png)
就这5个错误

**Comment by jcq15** [comment]
是按顺序运行的嘛，我这儿能跑（不过我也好久没用了，刷半天才嫖50原石）

**Comment by XueNianOfficial** [comment]
是啊

**Comment by jcq15** [comment]
我周末看看咋回事儿

**Comment by XueNianOfficial** [comment]
好，感谢
